services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    image: {{ cookiecutter.__package_slug }}
    build:
      context: ..
      dockerfile: .build/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg://user:password@db:5432/db
    depends_on:
      db:
        condition: service_healthy
    command:
      ["uvicorn", "{{ cookiecutter.__package_slug }}.{{ cookiecutter.__package_slug }}:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    restart: "no"

volumes:
  pgdata:
